// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Bkg1PK1RyoXEHdr6oYddvl777L3CRsA',
    appId: '1:1031073810417:web:e9774e24943e998975a650',
    messagingSenderId: '1031073810417',
    projectId: 'chatty-charm',
    authDomain: 'chatty-charm.firebaseapp.com',
    storageBucket: 'chatty-charm.appspot.com',
    measurementId: 'G-8XPBQLQ510',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQiolISpWC-jDscivqtg4YI7BOY_gFfI',
    appId: '1:1031073810417:android:42a18c297d1d46a075a650',
    messagingSenderId: '1031073810417',
    projectId: 'chatty-charm',
    storageBucket: 'chatty-charm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy4PCfQDfeC1OQBRJs2D3XwvAhv9BQog4',
    appId: '1:1031073810417:ios:0c92b8ef4bfd20be75a650',
    messagingSenderId: '1031073810417',
    projectId: 'chatty-charm',
    storageBucket: 'chatty-charm.appspot.com',
    iosBundleId: 'com.example.chattyCharm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy4PCfQDfeC1OQBRJs2D3XwvAhv9BQog4',
    appId: '1:1031073810417:ios:0c92b8ef4bfd20be75a650',
    messagingSenderId: '1031073810417',
    projectId: 'chatty-charm',
    storageBucket: 'chatty-charm.appspot.com',
    iosBundleId: 'com.example.chattyCharm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Bkg1PK1RyoXEHdr6oYddvl777L3CRsA',
    appId: '1:1031073810417:web:550b8ebaac4a0cf075a650',
    messagingSenderId: '1031073810417',
    projectId: 'chatty-charm',
    authDomain: 'chatty-charm.firebaseapp.com',
    storageBucket: 'chatty-charm.appspot.com',
    measurementId: 'G-P5XJ9J70ML',
  );
}
